### ISSUE TITLE
Set up continuous deployment to deno.land

### ISSUE THREAD

**Issue by filmaj** [ayame113/mock-file#12]
Thank you for maintaining and updating this project! It is extremely useful to many in the deno community, I am sure. ❤️ 

I noticed that there is a 1.1.0 tag on this repo. I am excited to use it! However, the latest released version on deno.land is 1.0.1.

May I suggest setting up continuous delivery in this project? For example, whenever a tag is pushed to the repo, it is easy to set up a webhook that automatically publishes code from that tag to deno.land. We at Slack use this setup to publish some of our deno libraries like [slackapi/deno-slack-runtime](https://github.com/slackapi/deno-slack-runtime) to [deno.land/x/deno_slack_runtime](https://deno.land/x/deno_slack_runtime).

If this interests you, deno.land has instructions on how to set it up: https://deno.land/add_module

In case it useful for you and as an example, for our deno-slack-runtime repository, the webhook in the GitHub repo's settings are as follows:

- The payload URL is https://api.deno.land/webhook/gh/deno_slack_runtime?subdir=src%2F
  - Note the `?subdir=src%2F` query parameter, this only applies if the code in the repo is located in a subdirectory called `src/`. I don't think mock-file would need that, since the main entry-point for this project is in the `mod.ts` located in the root of the project.
  - The URL for this project would need to change to match the deno.land module name. So I believe the URL for this project would be https://api.deno.land/webhook/gh/mock_file
- Only "Branch of tag creation" events are selected in the webhook events.

**Comment by ayame113** [comment]
Thank you for your suggestion!
But it looks like I already have a webhook to do that.

This is probably a known bug. (https://github.com/denoland/website_feedback/issues/25)
I will create a new tag again and see if the module is published.

**Comment by ayame113** [comment]
New version released! https://deno.land/x/mock_file@v1.1.2

Without your comment, I didn't realize the module was failing to publish. Thank you very much!
